package dbgirl.homecooking.pojo;

import java.io.Serializable;

public class Book implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.BOOK_NAME
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.IMAGE_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOK.DEFAUL_COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String defaulCookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.BOOK_ID
     *
     * @return the value of BOOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.BOOK_ID
     *
     * @param bookId the value for BOOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.BOOK_NAME
     *
     * @return the value of BOOK.BOOK_NAME
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.BOOK_NAME
     *
     * @param bookName the value for BOOK.BOOK_NAME
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.IMAGE_ID
     *
     * @return the value of BOOK.IMAGE_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.IMAGE_ID
     *
     * @param imageId the value for BOOK.IMAGE_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOK.DEFAUL_COOK_ID
     *
     * @return the value of BOOK.DEFAUL_COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getDefaulCookId() {
        return defaulCookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOK.DEFAUL_COOK_ID
     *
     * @param defaulCookId the value for BOOK.DEFAUL_COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setDefaulCookId(String defaulCookId) {
        this.defaulCookId = defaulCookId == null ? null : defaulCookId.trim();
    }

    @Override
    public String toString() {
        return "Book{" +
                "bookId='" + bookId + '\'' +
                ", bookName='" + bookName + '\'' +
                ", imageId='" + imageId + '\'' +
                ", defaulCookId='" + defaulCookId + '\'' +
                '}';
    }
}