package dbgirl.homecooking.pojo;

public class Cook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COOK.COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String cookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COOK.DETAIL
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COOK.COOK_ID
     *
     * @return the value of COOK.COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getCookId() {
        return cookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COOK.COOK_ID
     *
     * @param cookId the value for COOK.COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setCookId(String cookId) {
        this.cookId = cookId == null ? null : cookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COOK.BOOK_ID
     *
     * @return the value of COOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COOK.BOOK_ID
     *
     * @param bookId the value for COOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COOK.DETAIL
     *
     * @return the value of COOK.DETAIL
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COOK.DETAIL
     *
     * @param detail the value for COOK.DETAIL
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}