package dbgirl.homecooking.pojo;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGE.IMAGE_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IMAGE.IMAGE_BLOB
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private byte[] imageBlob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGE.IMAGE_ID
     *
     * @return the value of IMAGE.IMAGE_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGE.IMAGE_ID
     *
     * @param imageId the value for IMAGE.IMAGE_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAGE.IMAGE_BLOB
     *
     * @return the value of IMAGE.IMAGE_BLOB
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public byte[] getImageBlob() {
        return imageBlob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAGE.IMAGE_BLOB
     *
     * @param imageBlob the value for IMAGE.IMAGE_BLOB
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setImageBlob(byte[] imageBlob) {
        this.imageBlob = imageBlob;
    }
}