package dbgirl.homecooking.pojo;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.WECHAT_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String wechatId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_ID
     *
     * @return the value of USER.USER_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_ID
     *
     * @param userId the value for USER.USER_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.WECHAT_ID
     *
     * @return the value of USER.WECHAT_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.WECHAT_ID
     *
     * @param wechatId the value for USER.WECHAT_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }
}