package dbgirl.homecooking.pojo;

import java.io.Serializable;

public class UserBook implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_BOOK.USER_BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String userBookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_BOOK.USER_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_BOOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_BOOK.FAVORITE_COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    private String favoriteCookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_BOOK.USER_BOOK_ID
     *
     * @return the value of USER_BOOK.USER_BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getUserBookId() {
        return userBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_BOOK.USER_BOOK_ID
     *
     * @param userBookId the value for USER_BOOK.USER_BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setUserBookId(String userBookId) {
        this.userBookId = userBookId == null ? null : userBookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_BOOK.USER_ID
     *
     * @return the value of USER_BOOK.USER_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_BOOK.USER_ID
     *
     * @param userId the value for USER_BOOK.USER_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_BOOK.BOOK_ID
     *
     * @return the value of USER_BOOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_BOOK.BOOK_ID
     *
     * @param bookId the value for USER_BOOK.BOOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_BOOK.FAVORITE_COOK_ID
     *
     * @return the value of USER_BOOK.FAVORITE_COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getFavoriteCookId() {
        return favoriteCookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_BOOK.FAVORITE_COOK_ID
     *
     * @param favoriteCookId the value for USER_BOOK.FAVORITE_COOK_ID
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setFavoriteCookId(String favoriteCookId) {
        this.favoriteCookId = favoriteCookId == null ? null : favoriteCookId.trim();
    }
}