package dbgirl.homecooking.pojo;

import java.util.ArrayList;
import java.util.List;

public class UserBookExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public UserBookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserBookIdIsNull() {
            addCriterion("USER_BOOK_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserBookIdIsNotNull() {
            addCriterion("USER_BOOK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserBookIdEqualTo(String value) {
            addCriterion("USER_BOOK_ID =", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdNotEqualTo(String value) {
            addCriterion("USER_BOOK_ID <>", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdGreaterThan(String value) {
            addCriterion("USER_BOOK_ID >", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_BOOK_ID >=", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdLessThan(String value) {
            addCriterion("USER_BOOK_ID <", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdLessThanOrEqualTo(String value) {
            addCriterion("USER_BOOK_ID <=", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdLike(String value) {
            addCriterion("USER_BOOK_ID like", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdNotLike(String value) {
            addCriterion("USER_BOOK_ID not like", value, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdIn(List<String> values) {
            addCriterion("USER_BOOK_ID in", values, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdNotIn(List<String> values) {
            addCriterion("USER_BOOK_ID not in", values, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdBetween(String value1, String value2) {
            addCriterion("USER_BOOK_ID between", value1, value2, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserBookIdNotBetween(String value1, String value2) {
            addCriterion("USER_BOOK_ID not between", value1, value2, "userBookId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNull() {
            addCriterion("BOOK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("BOOK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(String value) {
            addCriterion("BOOK_ID =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(String value) {
            addCriterion("BOOK_ID <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(String value) {
            addCriterion("BOOK_ID >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(String value) {
            addCriterion("BOOK_ID >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(String value) {
            addCriterion("BOOK_ID <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(String value) {
            addCriterion("BOOK_ID <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLike(String value) {
            addCriterion("BOOK_ID like", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotLike(String value) {
            addCriterion("BOOK_ID not like", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<String> values) {
            addCriterion("BOOK_ID in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<String> values) {
            addCriterion("BOOK_ID not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(String value1, String value2) {
            addCriterion("BOOK_ID between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(String value1, String value2) {
            addCriterion("BOOK_ID not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdIsNull() {
            addCriterion("FAVORITE_COOK_ID is null");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdIsNotNull() {
            addCriterion("FAVORITE_COOK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdEqualTo(String value) {
            addCriterion("FAVORITE_COOK_ID =", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdNotEqualTo(String value) {
            addCriterion("FAVORITE_COOK_ID <>", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdGreaterThan(String value) {
            addCriterion("FAVORITE_COOK_ID >", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdGreaterThanOrEqualTo(String value) {
            addCriterion("FAVORITE_COOK_ID >=", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdLessThan(String value) {
            addCriterion("FAVORITE_COOK_ID <", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdLessThanOrEqualTo(String value) {
            addCriterion("FAVORITE_COOK_ID <=", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdLike(String value) {
            addCriterion("FAVORITE_COOK_ID like", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdNotLike(String value) {
            addCriterion("FAVORITE_COOK_ID not like", value, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdIn(List<String> values) {
            addCriterion("FAVORITE_COOK_ID in", values, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdNotIn(List<String> values) {
            addCriterion("FAVORITE_COOK_ID not in", values, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdBetween(String value1, String value2) {
            addCriterion("FAVORITE_COOK_ID between", value1, value2, "favoriteCookId");
            return (Criteria) this;
        }

        public Criteria andFavoriteCookIdNotBetween(String value1, String value2) {
            addCriterion("FAVORITE_COOK_ID not between", value1, value2, "favoriteCookId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_BOOK
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 18 16:50:35 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}