
spring:
  application:
    name: home-cooking
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/home-cooking?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT '1' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

mybatis:
  mapperLocations: classpath*:dao/mapper/*Mapper.xml
logging:
  config: classpath:logback-dev.xml
