package dbgirl.homecooking.dao;

import dbgirl.homecooking.pojo.Cook;
import dbgirl.homecooking.pojo.CookExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int countByExample(CookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int deleteByExample(CookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int deleteByPrimaryKey(String cookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int insert(Cook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int insertSelective(Cook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    List<Cook> selectByExampleWithBLOBs(CookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    List<Cook> selectByExample(CookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    Cook selectByPrimaryKey(String cookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Cook record, @Param("example") CookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Cook record, @Param("example") CookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExample(@Param("record") Cook record, @Param("example") CookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(Cook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Cook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByPrimaryKey(Cook record);
}