package dbgirl.homecooking.dao;

import dbgirl.homecooking.pojo.Image;
import dbgirl.homecooking.pojo.ImageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int deleteByPrimaryKey(String imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int insertSelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    List<Image> selectByExampleWithBLOBs(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    Image selectByPrimaryKey(String imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExample(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGE
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Image record);
}