package dbgirl.homecooking.dao;

import dbgirl.homecooking.pojo.UserBook;
import dbgirl.homecooking.pojo.UserBookExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UserBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int countByExample(UserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int deleteByExample(UserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int deleteByPrimaryKey(String userBookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int insert(UserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int insertSelective(UserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    List<UserBook> selectByExample(UserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    UserBook selectByPrimaryKey(String userBookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserBook record, @Param("example") UserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByExample(@Param("record") UserBook record, @Param("example") UserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(UserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BOOK
     *
     * @mbggenerated Sun Jun 18 16:50:35 CST 2017
     */
    int updateByPrimaryKey(UserBook record);
}